inherit_gem:
  govuk-lint: "configs/rubocop/all.yml"
AllCops:
    TargetRubyVersion: 2.3
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "config/routes.rb"
    - "config/environments/*.rb"
    - "app/domain/audits/filter.rb"

Rails/Presence:
  Exclude:
    - "app/domain/streams/messages/single_item_message.rb"

Rails/ApplicationRecord:
  Exclude:
    - "app/models/aggregations/materialized_view.rb"

Rails/ApplicationJob:
  Exclude:
    - "app/domain/streams/message_processor_job.rb"
