inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rails.yml"

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "db/migrate/201*.rb"
    - "db/schema.rb"

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "config/routes.rb"
    - "config/environments/*.rb"
    - "app/domain/audits/filter.rb"

Rails/Presence:
  Exclude:
    - "app/domain/streams/messages/single_item_message.rb"

Rails/ApplicationRecord:
  Exclude:
    - "app/models/aggregations/materialized_view.rb"

Rails/ApplicationJob:
  Exclude:
    - "app/domain/streams/message_processor_job.rb"

Rails/HasManyOrHasOneDependent:
  Exclude:
    - "app/models/events/publishing_api.rb"
    - "app/models/dimensions/edition.rb"

Rails/DynamicFindBy:
  Exclude:
    - "app/domain/finders/content.rb" # false positives
