language: ruby
services:
  - postgresql
rvm:
 - 2.3.1
script:
  - bundle exec govuk-lint-ruby app config db lib spec --format clang
  - bundle exec rake db:create db:migrate db:test:prepare
  - bundle exec rspec
addons:
  postgresql: "9.3"
