default: &default
  adapter: postgresql
  encoding: unicode
  pool: 12

development:
  <<: *default
  database: content_performance_manager_development
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] || ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: content_performance_manager_test
  url: <%= ENV['TEST_DATABASE_URL'] || ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: content_performance_manager_production
  username: content_performance_manager
  password: <%= ENV['CONTENT-PERFORMANCE-MANAGER_DATABASE_PASSWORD'] %>
