daily:
  - name: 'pviews'
    description: "Number of pageviews"
    source: 'Google Analytics'

  - name: 'upviews'
    description: "Number of unique pageviews"
    source: 'Google Analytics'

  - name: 'feedex' 
    description: "Number of reported content issues"
    source: 'Feedback explorer'

  - name: 'useful_no'
    description: "Total number of people who did not find the page helpful"
    source: 'Google Analytics'

  - name: 'useful_yes'
    description: "Total number of people who found the page helpful"
    source: 'Google Analytics'

  - name: 'satisfaction'
    description: "Calculated percentage score based on `is_this_useful_yes` and `is_this_useful_no` values."
    source: 'custom'

  - name: 'searches'
    description: "Number of times a user searches for something else on GOV.UK from the page"
    source: 'Google Analytics'

  - name: 'entrances'
    description: "Number of session that began with this page"
    source: 'Google Analytics'

  - name: 'exits'
    description: "Number of session that ended with this page"
    source: 'Google Analytics'

  - name: 'bounce_rate'
    description: "Number of sessions that started on this page and exited without viewing any others"
    source: 'Google Analytics'

  - name: 'avg_page_time'
    description: "Amount of time users spend on this page on average"
    source: 'Google Analytics'

edition:
  - name: 'number_of_pdfs'
    description: "Number of .pdf attachments"
    source: 'Publishing API'

  - name: 'number_of_word_files'
    description: "Number of .doc attachments"
    source: 'Publishing API'

  - name: 'readability_score'
    description: "Flesch-Kincaid Reading Ease score"

  - name: 'string_length'
    description: "Total number of characters used in the text"
    source: 'custom'

  - name: 'sentence_count'
    description: "Total number of sentences detected in the text"
    source: 'custom'

  - name: 'word_count'
    description: "Total number of words detected in the text"
    source: 'custom'
